// Import the signUpUser function from auth.js
import { signUpUser } from './auth.js';
document.getElementById('signup-form').addEventListener('submit', async function(event) {
  event.preventDefault();

  const firstName = document.getElementById('first-name').value.trim();
  const lastName = document.getElementById('last-name').value.trim();
  const email = document.getElementById('email').value.trim();
  const password = document.getElementById('password').value;
  const confirmPassword = document.getElementById('confirm-password').value;
  const role = document.querySelector('input[name="role"]:checked');  // Get the selected role

  // Clear previous messages
  const errorMessage = document.getElementById('error-message');
  const successMessage = document.getElementById('success-message');
  errorMessage.classList.add('hidden');
  successMessage.classList.add('hidden');

  if (!role) {
    // Show error message if no role is selected
    errorMessage.textContent = "Please select a role (Teacher or Learner).";
    errorMessage.classList.remove('hidden');
    return;
  }

  if (password !== confirmPassword) {
    // Show error message if passwords don't match
    errorMessage.textContent = "Passwords do not match.";
    errorMessage.classList.remove('hidden');
    return;
  }

  try {
    // Step 1: Use Supabase Auth to sign up
    const { user, error } = await supabase.auth.signUp({
      email: email,
      password: password,
    });

    if (error) {
      // Show error message if Supabase Auth fails
      throw new Error(error.message);
    }

    // Step 2: Insert user details into 'users' table
    const { data, insertError } = await supabase
      .from('users')
      .insert([
        {
          id: user.id,  // Use the user ID generated by Supabase Auth
          first_name: firstName,
          last_name: lastName,
          email: email,
          role: role.value,  // Store the selected role
        }
      ]);

    if (insertError) {
      // Show error message if inserting user info into 'users' table fails
      throw new Error(insertError.message);
    }

    // Step 3: Send a welcome email (optional)
    await sendWelcomeEmail(firstName, email);

    // Show success message
    successMessage.textContent = "Sign-up successful! A welcome email has been sent.";
    successMessage.classList.remove('hidden');

    // Redirect after a short delay
    setTimeout(function() {
      window.location.href = 'login.html';
    }, 2000);

  } catch (error) {
    // Show error message for any issues that occur
    errorMessage.textContent = error.message;
    errorMessage.classList.remove('hidden');
  }
});

// SendGrid email sending function (optional)
async function sendWelcomeEmail(firstName, email) {
  try {
    const response = await fetch('/sendgrid-email', {  // Assumes you have an endpoint for sending emails
      method: 'POST',
      body: JSON.stringify({
        to: email,
        subject: 'Welcome to FL EduAcademy',
        text: `Hello ${firstName}, welcome to FL EduAcademy! We're glad to have you on board.`
      }),
      headers: {
        'Content-Type': 'application/json',
      }
    });

    const result = await response.json();
    if (!result.success) {
      throw new Error("Failed to send email.");
    }
  } catch (emailError) {
    throw new Error("Error sending email: " + emailError.message);
  }
      }
